import {ClerkProvider} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { ConvexClientProvider } from "@/components/convex/ConvexClientProvider";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";


const inter = Inter({
  subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={inter.className}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <ConvexClientProvider>
          {children}
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}